name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: ventodeco/socio-echo-fe

jobs:
  test_build_push:
    environment: ENV_PRODUCTION
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up commit SHA tag
        id: vars
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ env.TAG }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ env.TAG }} 